# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-23 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admission Type', models.CharField(max_length=100)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10, max_length=10)),
            ],
        ),
    ]
