# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_auto_20160628_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='cost',
            field=models.CharField(max_length=10),
        ),
    ]
