# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_auto_20160628_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, max_length=10),
        ),
    ]
