# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0004_auto_20160626_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='percent',
            field=models.IntegerField(blank=True, max_length=3),
        ),
    ]
