# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 01:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0006_admissiontype_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admission.Organization'),
            preserve_default=False,
        ),
    ]
