# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0006_auto_20160626_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cash',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
