# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0007_event_cash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cash',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
