# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0007_event_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensetype',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admission.Event'),
            preserve_default=False,
        ),
    ]
