# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0008_expensetype_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_type', models.CharField(max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.Event')),
            ],
        ),
        migrations.AddField(
            model_name='income',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.IncomeType'),
        ),
    ]
