# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0009_auto_20160629_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admission.Event'),
            preserve_default=False,
        ),
    ]
